jobs:
  build-branches:
    environment:
      Harbor_Git_Tag: 'v2.10.0-rc2'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build a container image
          command: |
            bash build-harbor-aarch64.sh
            docker images
            docker tag goharbor/prepare:${Harbor_Git_Tag}-arm goharbor/prepare:dev-arm
            mkdir all-in-one/harbor
            docker save $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "^goharbor/"| grep "\-arm") | gzip > all-in-one/harbor/harbor.${Harbor_Git_Tag}.tar.gz
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/LICENSE -o all-in-one/harbor/LICENSE
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/make/common.sh -o all-in-one/harbor/common.sh
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/make/harbor.yml.tmpl -o all-in-one/harbor/harbor.yml.tmpl
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/make/install.sh -o all-in-one/harbor/install.sh
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/make/prepare -o all-in-one/harbor/prepare
            sed -i 's#goharbor/prepare:dev#goharbor/prepare:dev-arm#g' all-in-one/harbor/prepare
            cd all-in-one
            chmod +x harbor/prepare harbor/install.sh
            tar zcf harbor-offline-installer-aarch64.tgz harbor
            rm -rf harbor
            docker build -t alanpeng/harbor_images_aarch64:$Harbor_Git_Tag .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push alanpeng/harbor_images_aarch64:$Harbor_Git_Tag
            #bash get-images.sh
  build-tags:
    environment:
      Harbor_Git_Tag: 'v2.10.0-rc2'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build a container image
          command: |
            bash build-harbor-aarch64.sh
            docker images
            mkdir all-in-one/harbor
            docker save $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "^goharbor/") | gzip > all-in-one/harbor/harbor.${Harbor_Git_Tag}.tar.gz
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/LICENSE -o all-in-one/harbor/LICENSE
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/make/common.sh -o all-in-one/harbor/common.sh
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/make/harbor.yml.tmpl -o all-in-one/harbor/harbor.yml.tmpl
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/make/install.sh -o all-in-one/harbor/install.sh
            curl -L https://raw.githubusercontent.com/vmware/harbor/${Harbor_Git_Tag}/make/prepare -o all-in-one/harbor/prepare
            sed -i 's#goharbor/prepare:dev#goharbor/prepare:dev-arm#g' all-in-one/harbor/prepare
            cd all-in-one
            chmod +x harbor/prepare harbor/install.sh
            tar zcf harbor-offline-installer-aarch64.tgz harbor
            rm -rf harbor
            docker build -t alanpeng/harbor_images_aarch64:$Harbor_Git_Tag .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push alanpeng/harbor_images_aarch64:$Harbor_Git_Tag
            #bash get-images.sh
workflows:
  version: 2
  build-for-branches:
    jobs:
      - build-branches
  build-for-tags:
    jobs:
      - build-tags:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
